server:
  port: 8888
  servlet:
    context-path: /api #访问前缀
spring:
  application:
    name: demo-video
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.201.255.155:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jmx:
    enabled: false
logging:
  level:
    root: warn
  pattern:
    console: '%p%m%n'
#mybatisplus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
#fastDFS
fdfs:
  so-timeout: 15010
  connect-timeout: 6010
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 101.201.255.155:22122